export type Rarity = "common" | "uncommon" | "rare" | "epic" | "legendary"

export type TurtleDefinition = {
  id: string
  name: string
  rarity: Rarity
  description: string
  unlockHint: string
  emoji: string
  shellColor: string
  shellPattern?: "solid" | "striped" | "spotted" | "gradient" | "glowing"
}

export const rarityOrder: Record<Rarity, number> = {
  common: 0,
  uncommon: 1,
  rare: 2,
  epic: 3,
  legendary: 4,
}

export const rarityColors: Record<Rarity, string> = {
  common: "#94A3B8",
  uncommon: "#6BCF9A",
  rare: "#7FD8F7",
  epic: "#D8C8FF",
  legendary: "#FFE89C",
}

export const rarityLabels: Record<Rarity, string> = {
  common: "Common",
  uncommon: "Uncommon",
  rare: "Rare",
  epic: "Epic",
  legendary: "Legendary",
}

export const turtleDefinitions: TurtleDefinition[] = [
  {
    id: "baby",
    name: "Baby Turtle",
    rarity: "common",
    description: "A tiny turtle that just hatched. So full of wonder!",
    unlockHint: "Find it relaxing in Turtle Village",
    emoji: "🐢",
    shellColor: "#6BCF9A",
    shellPattern: "solid",
  },
  {
    id: "sleepy",
    name: "Sleepy Turtle",
    rarity: "common",
    description: "Always yawning. Loves naps in sunny spots.",
    unlockHint: "Visit at just the right moment in Turtle Village",
    emoji: "💤",
    shellColor: "#94A3B8",
    shellPattern: "solid",
  },
  {
    id: "flower",
    name: "Flower Turtle",
    rarity: "common",
    description: "Has a flower growing on its shell. Loves gardens.",
    unlockHint: "Explore the Flower Garden",
    emoji: "🌸",
    shellColor: "#FFA8A8",
    shellPattern: "spotted",
  },
  {
    id: "bee",
    name: "Bee Turtle",
    rarity: "common",
    description: "Buzzy and bright. Always humming a little tune.",
    unlockHint: "Check the Flower Garden during golden hour",
    emoji: "🐝",
    shellColor: "#FFE89C",
    shellPattern: "striped",
  },
  {
    id: "ocean",
    name: "Ocean Turtle",
    rarity: "common",
    description: "Carries a tiny ocean on its back. Waves gently.",
    unlockHint: "Splash around at Heart Lake",
    emoji: "🌊",
    shellColor: "#7FD8F7",
    shellPattern: "gradient",
  },
  {
    id: "cloud",
    name: "Cloud Turtle",
    rarity: "common",
    description: "So light it almost floats. Made of dreams.",
    unlockHint: "Look up at the Cloud Observatory",
    emoji: "☁️",
    shellColor: "#E2E8F0",
    shellPattern: "solid",
  },
  {
    id: "chef",
    name: "Chef Turtle",
    rarity: "uncommon",
    description: "Wears a tiny chef hat. Makes the best seaweed soup.",
    unlockHint: "Visit during lunch time in Turtle Village",
    emoji: "🍳",
    shellColor: "#FFA8A8",
    shellPattern: "solid",
  },
  {
    id: "pirate",
    name: "Pirate Turtle",
    rarity: "uncommon",
    description: "Lost an eye in a great adventure. Still sails on!",
    unlockHint: "Search near the water at Heart Lake",
    emoji: "🏴‍☠️",
    shellColor: "#8B4513",
    shellPattern: "striped",
  },
  {
    id: "detective",
    name: "Detective Turtle",
    rarity: "uncommon",
    description: "Solves mysteries with a magnifying glass. Very serious.",
    unlockHint: "Investigate the Treasure Cave area",
    emoji: "🔍",
    shellColor: "#4A5568",
    shellPattern: "solid",
  },
  {
    id: "ghost",
    name: "Ghost Turtle",
    rarity: "uncommon",
    description: "Boo! A friendly little spirit. Passes through walls.",
    unlockHint: "Appears at dusk in the Treasure Cave",
    emoji: "👻",
    shellColor: "#A78BFA",
    shellPattern: "glowing",
  },
  {
    id: "dino",
    name: "Dino Turtle",
    rarity: "uncommon",
    description: "Thinks it's a dinosaur. Roars adorably.",
    unlockHint: "Hang out in Dino Valley",
    emoji: "🦕",
    shellColor: "#6BCF9A",
    shellPattern: "spotted",
  },
  {
    id: "pudding",
    name: "Pudding Turtle",
    rarity: "uncommon",
    description: "Jiggly and sweet. Smells like vanilla.",
    unlockHint: "Dessert time in Turtle Village",
    emoji: "🍮",
    shellColor: "#FDE68A",
    shellPattern: "solid",
  },
  {
    id: "wizard",
    name: "Wizard Turtle",
    rarity: "rare",
    description: "Casts spells with a tiny wand. Knows ancient secrets.",
    unlockHint: "Found in a magical corner of the island",
    emoji: "🧙",
    shellColor: "#D8C8FF",
    shellPattern: "gradient",
  },
  {
    id: "princess",
    name: "Princess Turtle",
    rarity: "rare",
    description: "A regal turtle with a sparkling crown. Very graceful.",
    unlockHint: "Visit the Flower Garden in bloom",
    emoji: "👑",
    shellColor: "#FFA8A8",
    shellPattern: "glowing",
  },
  {
    id: "astronaut",
    name: "Astronaut Turtle",
    rarity: "rare",
    description: "Dreams of the stars. Has been to the moon and back.",
    unlockHint: "Gaze at the stars at Cloud Observatory",
    emoji: "🚀",
    shellColor: "#7FD8F7",
    shellPattern: "gradient",
  },
  {
    id: "knight",
    name: "Knight Turtle",
    rarity: "rare",
    description: "Brave and true. Guards the island with honor.",
    unlockHint: "Stand guard at the Treasure Cave entrance",
    emoji: "⚔️",
    shellColor: "#94A3B8",
    shellPattern: "solid",
  },
  {
    id: "fairy",
    name: "Fairy Turtle",
    rarity: "rare",
    description: "Sprinkles stardust everywhere. Wings made of light.",
    unlockHint: "Visit the Flower Garden at twilight",
    emoji: "🧚",
    shellColor: "#E8D5F5",
    shellPattern: "glowing",
  },
  {
    id: "galaxy",
    name: "Galaxy Turtle",
    rarity: "epic",
    description: "Its shell contains an entire universe. Mesmerizing.",
    unlockHint: "Reach 30 stars to reveal its location",
    emoji: "🌌",
    shellColor: "#1E1B4B",
    shellPattern: "glowing",
  },
  {
    id: "rainbow",
    name: "Rainbow Turtle",
    rarity: "epic",
    description: "A prismatic wonder. Leaves rainbows wherever it goes.",
    unlockHint: "Found deep in the Treasure Cave",
    emoji: "🌈",
    shellColor: "url(#rainbow)",
    shellPattern: "gradient",
  },
  {
    id: "crystal",
    name: "Crystal Turtle",
    rarity: "epic",
    description: "Made of pure crystal. Shines with inner light.",
    unlockHint: "Explore deep within Heart Lake",
    emoji: "💎",
    shellColor: "#D8C8FF",
    shellPattern: "glowing",
  },
  {
    id: "ninja",
    name: "Ninja Turtle",
    rarity: "epic",
    description: "Master of stealth. Moves so quietly... wait, where'd it go?",
    unlockHint: "Complete all three mini-games",
    emoji: "🥷",
    shellColor: "#1F2937",
    shellPattern: "solid",
  },
  {
    id: "golden",
    name: "Golden Turtle",
    rarity: "legendary",
    description: "Legends say whoever finds the Golden Turtle is blessed with eternal happiness.",
    unlockHint: "Collect 50 stars to summon it",
    emoji: "⭐",
    shellColor: "#FFD700",
    shellPattern: "glowing",
  },
  {
    id: "moon",
    name: "Moon Turtle",
    rarity: "legendary",
    description: "Born from moonlight. Glows softly in the dark.",
    unlockHint: "Visit the Cloud Observatory under a new moon",
    emoji: "🌙",
    shellColor: "#FDE68A",
    shellPattern: "glowing",
  },
  {
    id: "sun",
    name: "Sun Turtle",
    rarity: "legendary",
    description: "Radiates warmth and light. The source of all joy on the island.",
    unlockHint: "Collect all common turtles first",
    emoji: "☀️",
    shellColor: "#F59E0B",
    shellPattern: "glowing",
  },
  {
    id: "star",
    name: "Star Turtle",
    rarity: "legendary",
    description: "Made of pure starlight. Grants wishes to pure hearts.",
    unlockHint: "Find all rare turtles",
    emoji: "🌟",
    shellColor: "#FDE68A",
    shellPattern: "glowing",
  },
  {
    id: "magma",
    name: "Magma Turtle",
    rarity: "epic",
    description: "Hot to the touch. Leaves tiny scorch marks. Very warm hug.",
    unlockHint: "Visit Dino Valley during sunset",
    emoji: "🌋",
    shellColor: "#EF4444",
    shellPattern: "gradient",
  },
  {
    id: "forest",
    name: "Forest Turtle",
    rarity: "uncommon",
    description: "Moss grows on its shell. Home to tiny ladybugs.",
    unlockHint: "Wander the paths of Turtle Village",
    emoji: "🌲",
    shellColor: "#166534",
    shellPattern: "spotted",
  },
  {
    id: "bubble",
    name: "Bubble Turtle",
    rarity: "rare",
    description: "Blows perfect iridescent bubbles. Each one carries a dream.",
    unlockHint: "Play Bubble Pop until you score 15",
    emoji: "🫧",
    shellColor: "#7FD8F7",
    shellPattern: "gradient",
  },
  {
    id: "heart",
    name: "Heart Turtle",
    rarity: "epic",
    description: "Covered in tiny hearts. Loves everyone unconditionally.",
    unlockHint: "Pop 50 ripples at Heart Lake",
    emoji: "❤️",
    shellColor: "#FFA8A8",
    shellPattern: "spotted",
  },
  {
    id: "cosmic",
    name: "Cosmic Turtle",
    rarity: "legendary",
    description: "Ancient being that carries the universe. Exists beyond time.",
    unlockHint: "Collect 80% of all turtles",
    emoji: "🌠",
    shellColor: "#2E1065",
    shellPattern: "glowing",
  },
]

export function getTurtleDef(id: string): TurtleDefinition | undefined {
  return turtleDefinitions.find((t) => t.id === id)
}

export function getTurtlesByRarity(rarity: Rarity): TurtleDefinition[] {
  return turtleDefinitions.filter((t) => t.rarity === rarity)
}
